package com.bean_scope_and_mapping.spring_data_and_mapping.mapping_inheritence_as_table_per_class.repository;

import org.springframework.stereotype.Repository;

@Repository
public interface MobileOneBatteryOnePhoneRepository extends MobileOnePhoneRepository {
}
