package com.bean_scope_and_mapping.spring_data_and_mapping.mapping_inheritence_without_generating_super_class.repository;

import com.bean_scope_and_mapping.spring_data_and_mapping.mapping_inheritence_without_generating_super_class.Vehicles;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.repository.NoRepositoryBean;

@NoRepositoryBean
public interface VehicleRepository extends JpaRepository<Vehicles, Long> {
}
